apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-results-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-results-server
  template:
    metadata:
      labels:
        app: lab-results-server
    spec:
      containers:
        - name: server
          image: ghcr.io/your-org/lab-results-server:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: MIRTH_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MIRTH_WEBHOOK_SECRET
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lab-results-server
spec:
  selector:
    app: lab-results-server
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http